# Generated by Django 5.2.12 on 2026-03-24 07:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("celery_task_id", models.CharField(db_index=True, max_length=255, unique=True)),
                ("task_name", models.CharField(max_length=255)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("command", "一次性指令"),
                            ("sync", "同步任務"),
                            ("analysis", "分析/AI 長任務"),
                        ],
                        default="command",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "執行中"),
                            ("success", "成功"),
                            ("failed", "失敗"),
                            ("retrying", "重試中"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=255)),
                ("user_id", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "db_table": "_task_queue_taskprogress",
                "ordering": ["-created_at"],
            },
        ),
    ]
