# Generated by Django 5.2.12 on 2026-05-01 14:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("generation_jobs", "0002_generationjob_metadata_file_and_more"),
        ("style_presets", "0005_refresh_processor_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentGenerationSession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING_APPROVAL", "等待確認"),
                            ("GENERATING", "生成中"),
                            ("COMPLETED", "已完成"),
                            ("PARTIAL", "部分完成"),
                            ("FAILED", "失敗"),
                            ("CANCELED", "已取消"),
                        ],
                        db_index=True,
                        default="WAITING_APPROVAL",
                        max_length=24,
                        verbose_name="狀態",
                    ),
                ),
                ("brief", models.TextField(verbose_name="使用者需求")),
                ("output_name", models.CharField(max_length=120, verbose_name="素材包名稱")),
                (
                    "game_genre",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="遊戲類型"
                    ),
                ),
                (
                    "camera_view",
                    models.CharField(default="top-down", max_length=40, verbose_name="視角"),
                ),
                (
                    "style_mode",
                    models.CharField(default="agent", max_length=20, verbose_name="風格模式"),
                ),
                ("auto_generate", models.BooleanField(default=False, verbose_name="自動生成")),
                (
                    "max_retry_per_item",
                    models.PositiveSmallIntegerField(default=2, verbose_name="項目最大重試次數"),
                ),
                (
                    "manifest",
                    models.JSONField(blank=True, default=dict, verbose_name="Agent Manifest"),
                ),
                (
                    "planning_steps",
                    models.JSONField(blank=True, default=list, verbose_name="規劃步驟"),
                ),
                ("error", models.TextField(blank=True, default="", verbose_name="錯誤訊息")),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="確認時間"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="開始時間"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成時間"),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agent_generation_sessions",
                        to="style_presets.stylepreset",
                        verbose_name="風格預設",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_generation_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 生圖 Session",
                "verbose_name_plural": "Agent 生圖 Sessions",
                "db_table": "agent_generation_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentGenerationItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "已規劃"),
                            ("QUEUED", "已排隊"),
                            ("GENERATING", "生成中"),
                            ("ARCHIVED", "已完成"),
                            ("FAILED", "失敗"),
                            ("CANCELED", "已取消"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("category", models.CharField(max_length=80, verbose_name="分類")),
                ("name", models.CharField(max_length=120, verbose_name="名稱")),
                ("subject", models.CharField(max_length=500, verbose_name="生成主題")),
                (
                    "asset_type",
                    models.CharField(default="prop", max_length=40, verbose_name="素材類型"),
                ),
                ("prompt_brief", models.TextField(blank=True, default="", verbose_name="生成意圖")),
                (
                    "sort_order",
                    models.PositiveIntegerField(db_index=True, default=0, verbose_name="排序"),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="重試次數"),
                ),
                ("last_error", models.TextField(blank=True, default="", verbose_name="最後錯誤")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "generation_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_generation_items",
                        to="generation_jobs.generationjob",
                        verbose_name="生成任務",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="agent_generation.agentgenerationsession",
                        verbose_name="Agent Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 生圖項目",
                "verbose_name_plural": "Agent 生圖項目",
                "db_table": "agent_generation_item",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentGenerationAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(default=1, verbose_name="嘗試次數"),
                ),
                ("status", models.CharField(default="QUEUED", max_length=20, verbose_name="狀態")),
                ("error", models.TextField(blank=True, default="", verbose_name="錯誤訊息")),
                (
                    "prompt_snapshot",
                    models.TextField(blank=True, default="", verbose_name="Prompt 快照"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "generation_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_generation_attempts",
                        to="generation_jobs.generationjob",
                        verbose_name="生成任務",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="agent_generation.agentgenerationitem",
                        verbose_name="Agent 項目",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 生圖嘗試",
                "verbose_name_plural": "Agent 生圖嘗試",
                "db_table": "agent_generation_attempt",
                "ordering": ["item", "attempt_number"],
                "indexes": [
                    models.Index(
                        fields=["item", "attempt_number"], name="agent_gener_item_id_27d491_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agentgenerationsession",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="agent_gener_user_id_ebc85c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentgenerationitem",
            index=models.Index(
                fields=["session", "status", "sort_order"], name="agent_gener_session_f7534d_idx"
            ),
        ),
    ]
