# Generated by Django 5.2.12 on 2026-05-04

import uuid

import django.db.models.deletion
from django.db import migrations, models


def migrate_agent_session_state(apps, schema_editor):
    session_model = apps.get_model("agent_generation", "AgentGenerationSession")
    for session in session_model.objects.all().only("id", "status", "updated_at", "created_at"):
        if session.status == "WAITING_APPROVAL":
            session.status = "CHATTING"
        session.latest_chat_at = session.updated_at or session.created_at
        session.save(update_fields=["status", "latest_chat_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("agent_generation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentGenerationMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "使用者"),
                            ("assistant", "Agent"),
                            ("system", "系統"),
                        ],
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="訊息內容")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="agent_generation.agentgenerationsession",
                        verbose_name="Agent Session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent 對話訊息",
                "verbose_name_plural": "Agent 對話訊息",
                "db_table": "agent_generation_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="agentgenerationsession",
            name="asset_requirements",
            field=models.JSONField(blank=True, default=dict, verbose_name="素材需求數量"),
        ),
        migrations.AddField(
            model_name="agentgenerationsession",
            name="context",
            field=models.JSONField(blank=True, default=dict, verbose_name="對話萃取狀態"),
        ),
        migrations.AddField(
            model_name="agentgenerationsession",
            name="latest_chat_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最後使用者聊天時間"),
        ),
        migrations.AlterField(
            model_name="agentgenerationsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("CHATTING", "對話中"),
                    ("PLANNING", "規劃中"),
                    ("GENERATING", "生成中"),
                    ("COMPLETED", "已完成"),
                    ("PARTIAL", "部分完成"),
                    ("FAILED", "失敗"),
                    ("CANCELED", "已取消"),
                ],
                db_index=True,
                default="CHATTING",
                max_length=24,
                verbose_name="狀態",
            ),
        ),
        migrations.AlterField(
            model_name="agentgenerationsession",
            name="brief",
            field=models.TextField(blank=True, default="", verbose_name="使用者需求摘要"),
        ),
        migrations.AlterField(
            model_name="agentgenerationsession",
            name="output_name",
            field=models.CharField(
                blank=True,
                default="AgentPack",
                max_length=120,
                verbose_name="素材包名稱",
            ),
        ),
        migrations.AlterField(
            model_name="agentgenerationsession",
            name="camera_view",
            field=models.CharField(blank=True, default="", max_length=40, verbose_name="視角"),
        ),
        migrations.AlterField(
            model_name="agentgenerationsession",
            name="auto_generate",
            field=models.BooleanField(default=True, verbose_name="自動生成"),
        ),
        migrations.AlterModelOptions(
            name="agentgenerationsession",
            options={
                "db_table": "agent_generation_session",
                "ordering": ["-latest_chat_at", "-created_at"],
                "verbose_name": "Agent 生圖 Session",
                "verbose_name_plural": "Agent 生圖 Sessions",
            },
        ),
        migrations.RunPython(migrate_agent_session_state, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="agentgenerationsession",
            name="latest_chat_at",
            field=models.DateTimeField(db_index=True, verbose_name="最後使用者聊天時間"),
        ),
        migrations.RemoveIndex(
            model_name="agentgenerationsession",
            name="agent_gener_user_id_ebc85c_idx",
        ),
        migrations.AddIndex(
            model_name="agentgenerationsession",
            index=models.Index(
                fields=["user", "status", "-latest_chat_at"], name="agent_gener_user_id_e60fd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentgenerationmessage",
            index=models.Index(
                fields=["session", "created_at"], name="agent_gener_session_a324a3_idx"
            ),
        ),
    ]
