# Generated by Django 5.2.12 on 2026-05-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_generation", "0002_chat_sessions_and_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentgenerationmessage",
            name="client_message_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120, verbose_name="前端訊息 ID"
            ),
        ),
        migrations.AddField(
            model_name="agentgenerationsession",
            name="last_orchestration_task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=255,
                verbose_name="最後 Agent 任務 ID",
            ),
        ),
        migrations.AddField(
            model_name="agentgenerationsession",
            name="last_processed_message_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="最後已處理訊息 ID"),
        ),
        migrations.AddField(
            model_name="agentgenerationsession",
            name="processing_message_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="處理中訊息 ID"),
        ),
        migrations.AddField(
            model_name="agentgenerationsession",
            name="processing_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="處理開始時間"),
        ),
        migrations.AddIndex(
            model_name="agentgenerationmessage",
            index=models.Index(fields=["client_message_id"], name="agent_gener_client__a5bc88_idx"),
        ),
        migrations.AddConstraint(
            model_name="agentgenerationmessage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_message_id", ""), _negated=True),
                fields=("session", "client_message_id"),
                name="agent_message_session_client_uid",
            ),
        ),
    ]
