# Generated by Django 5.2.12 on 2026-03-31 05:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系統通知"),
                            ("security", "安全通知"),
                            ("billing", "帳務通知"),
                            ("marketing", "行銷通知"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=20,
                        verbose_name="分類",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("body", models.TextField(verbose_name="內文")),
                ("html_body", models.TextField(blank=True, default="", verbose_name="HTML 內文")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="附加資料")),
                ("action_url", models.URLField(blank=True, default="", verbose_name="操作連結")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "一般"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="優先級",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理"),
                            ("queued", "已排入佇列"),
                            ("sent", "已發送"),
                            ("delivered", "已送達"),
                            ("read", "已讀"),
                            ("failed", "失敗"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("read_at", models.DateTimeField(blank=True, null=True, verbose_name="已讀時間")),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="排程時間"),
                ),
                (
                    "source_event",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="來源事件"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("channel", models.CharField(max_length=30, verbose_name="頻道")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待處理"),
                            ("queued", "已排入佇列"),
                            ("sent", "已發送"),
                            ("delivered", "已送達"),
                            ("read", "已讀"),
                            ("failed", "失敗"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="外部 ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="錯誤訊息"),
                ),
                ("retry_count", models.PositiveIntegerField(default=0, verbose_name="重試次數")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="發送時間")),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="送達時間"),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                        verbose_name="通知",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system", "系統通知"),
                            ("security", "安全通知"),
                            ("billing", "帳務通知"),
                            ("marketing", "行銷通知"),
                        ],
                        max_length=20,
                        verbose_name="分類",
                    ),
                ),
                ("enabled_channels", models.JSONField(default=list, verbose_name="啟用頻道")),
                ("is_muted", models.BooleanField(default=False, verbose_name="靜音")),
                (
                    "quiet_hours_start",
                    models.TimeField(blank=True, null=True, verbose_name="免打擾開始時間"),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(blank=True, null=True, verbose_name="免打擾結束時間"),
                ),
                (
                    "quiet_hours_timezone",
                    models.CharField(
                        default="Asia/Taipei", max_length=50, verbose_name="免打擾時區"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="notificatio_user_id_eebdc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "category", "-created_at"], name="notificatio_user_id_c6dff0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationdelivery",
            unique_together={("notification", "channel")},
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("user", "category")},
        ),
    ]
