# Generated by Django 5.2.12 on 2026-03-31 05:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('max_bytes', models.BigIntegerField(default=1073741824)),
                ('used_bytes', models.BigIntegerField(default=0)),
                ('max_file_count', models.PositiveIntegerField(default=10000)),
                ('used_file_count', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('storage_backend', models.CharField(default='local', max_length=30)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('etag', models.CharField(blank=True, default='', max_length=200)),
                ('visibility', models.CharField(choices=[('private', '私有（僅上傳者）'), ('public', '公開'), ('shared', '共享（指定使用者）')], default='private', max_length=10)),
                ('status', models.CharField(choices=[('pending', '待確認（Presigned 上傳中）'), ('confirmed', '已確認'), ('expired', '已過期（Presigned 未完成上傳）'), ('deleted', '已刪除')], default='confirmed', max_length=10)),
                ('folder', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('presign_expires_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=100)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'folder', '-created_at'], name='file_storag_owner_i_ff8928_idx'), models.Index(fields=['storage_backend', 'status'], name='file_storag_storage_4a08a8_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='file_storag_related_0b7fcb_idx')],
            },
        ),
    ]
