"""操作審計日誌常數定義。"""

# 敏感欄位清單 — 這些欄位在寫入審計記錄前會被過濾
SENSITIVE_PAYLOAD_KEYS = {
    "password",
    "api_key",
    "secret",
    "token",
    "key_hash",
    "access_token",
    "refresh_token",
}

# 可審計事件映射表 — event_type 對應審計記錄的分類、動作、嚴重程度等
AUDITABLE_EVENTS = {
    # ── 認證事件 ──────────────────────────────────────
    # actor_id_key: 指定 payload 中哪個欄位代表操作者 ID，預設為 "user_id"
    "auth.user.logged_in": {
        "category": "auth",
        "action": "logged_in",
        "severity": "info",
        "description": "使用者登入",
        "resource_type": "accounts.user",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
    "auth.user.logged_out": {
        "category": "auth",
        "action": "logged_out",
        "severity": "info",
        "description": "使用者登出",
        "resource_type": "accounts.user",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
    "auth.user.registered": {
        "category": "auth",
        "action": "registered",
        "severity": "info",
        "description": "使用者註冊",
        "resource_type": "accounts.user",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
    "auth.password_reset.requested": {
        "category": "security",
        "action": "password_reset_requested",
        "severity": "warning",
        "description": "密碼重設請求",
        "resource_type": "accounts.user",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
    "auth.password.changed": {
        "category": "security",
        "action": "password_changed",
        "severity": "warning",
        "description": "密碼已變更",
        "resource_type": "accounts.user",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
    "accounts.profile.updated": {
        "category": "account",
        "action": "profile_updated",
        "severity": "info",
        "description": "個人資料更新",
        "resource_type": "accounts.user",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
    # ── 付款事件 ──────────────────────────────────────
    "payments.transaction.created": {
        "category": "payment",
        "action": "created",
        "severity": "info",
        "description": "交易建立",
        "resource_type": "payments.transaction",
        "resource_id_key": "transaction_id",
        "actor_id_key": "user_id",
    },
    "payments.transaction.succeeded": {
        "category": "payment",
        "action": "succeeded",
        "severity": "info",
        "description": "交易成功",
        "resource_type": "payments.transaction",
        "resource_id_key": "transaction_id",
        "actor_id_key": "user_id",
    },
    "payments.transaction.failed": {
        "category": "payment",
        "action": "failed",
        "severity": "warning",
        "description": "交易失敗",
        "resource_type": "payments.transaction",
        "resource_id_key": "transaction_id",
        "actor_id_key": "user_id",
    },
    # ── API 金鑰事件 ──────────────────────────────────
    "api_keys.key.created": {
        "category": "api_keys",
        "action": "created",
        "severity": "info",
        "description": "API 金鑰建立",
        "resource_type": "api_keys.apikey",
        "resource_id_key": "key_id",
        "actor_id_key": "user_id",
    },
    "api_keys.key.revoked": {
        "category": "api_keys",
        "action": "revoked",
        "severity": "warning",
        "description": "API 金鑰撤銷",
        "resource_type": "api_keys.apikey",
        "resource_id_key": "key_id",
        "actor_id_key": "user_id",
    },
    "api_keys.key.rotated": {
        "category": "api_keys",
        "action": "rotated",
        "severity": "info",
        "description": "API 金鑰輪換",
        "resource_type": "api_keys.apikey",
        "resource_id_key": "key_id",
        "actor_id_key": "user_id",
    },
    "api_keys.key.disabled": {
        "category": "api_keys",
        "action": "disabled",
        "severity": "info",
        "description": "API 金鑰停用",
        "resource_type": "api_keys.apikey",
        "resource_id_key": "key_id",
        "actor_id_key": "user_id",
    },
    "api_keys.key.enabled": {
        "category": "api_keys",
        "action": "enabled",
        "severity": "info",
        "description": "API 金鑰啟用",
        "resource_type": "api_keys.apikey",
        "resource_id_key": "key_id",
        "actor_id_key": "user_id",
    },
    # ── RBAC 角色與權限事件 ─────────────────────────────
    "rbac.role.created": {
        "category": "rbac",
        "action": "role_created",
        "severity": "info",
        "description": "角色建立",
        "resource_type": "rbac.role",
        "resource_id_key": "role_id",
        "actor_id_key": "user_id",
    },
    "rbac.role.updated": {
        "category": "rbac",
        "action": "role_updated",
        "severity": "info",
        "description": "角色更新",
        "resource_type": "rbac.role",
        "resource_id_key": "role_id",
        "actor_id_key": "user_id",
    },
    "rbac.role.deleted": {
        "category": "rbac",
        "action": "role_deleted",
        "severity": "warning",
        "description": "角色刪除",
        "resource_type": "rbac.role",
        "resource_id_key": "role_id",
        "actor_id_key": "user_id",
    },
    "rbac.role.permissions_updated": {
        "category": "rbac",
        "action": "permissions_updated",
        "severity": "info",
        "description": "角色權限變更",
        "resource_type": "rbac.role",
        "resource_id_key": "role_id",
        "actor_id_key": "user_id",
    },
    "rbac.role.assigned": {
        "category": "rbac",
        "action": "role_assigned",
        "severity": "info",
        "description": "使用者角色指派",
        "resource_type": "rbac.userrole",
        "resource_id_key": "user_id",
        "actor_id_key": "assigned_by",
    },
    "rbac.role.removed": {
        "category": "rbac",
        "action": "role_removed",
        "severity": "warning",
        "description": "使用者角色移除",
        "resource_type": "rbac.userrole",
        "resource_id_key": "user_id",
        "actor_id_key": "removed_by",
    },
    # ── 檔案儲存事件 ──────────────────────────────────
    "file_storage.file.uploaded": {
        "category": "file_storage",
        "action": "uploaded",
        "severity": "info",
        "description": "檔案上傳",
        "resource_type": "file_storage.filerecord",
        "resource_id_key": "file_id",
        "actor_id_key": "user_id",
    },
    "file_storage.file.confirmed": {
        "category": "file_storage",
        "action": "confirmed",
        "severity": "info",
        "description": "預簽名上傳確認",
        "resource_type": "file_storage.filerecord",
        "resource_id_key": "file_id",
        "actor_id_key": "user_id",
    },
    "file_storage.file.deleted": {
        "category": "file_storage",
        "action": "deleted",
        "severity": "warning",
        "description": "檔案刪除",
        "resource_type": "file_storage.filerecord",
        "resource_id_key": "file_id",
        "actor_id_key": "user_id",
    },
    "file_storage.file.downloaded": {
        "category": "file_storage",
        "action": "downloaded",
        "severity": "info",
        "description": "檔案下載",
        "resource_type": "file_storage.filerecord",
        "resource_id_key": "file_id",
        "actor_id_key": "user_id",
    },
    # ── 通知事件 ────────────────────────────────────
    "notifications.notification.created": {
        "category": "notifications",
        "action": "created",
        "severity": "info",
        "description": "通知發送",
        "resource_type": "notifications.notification",
        "resource_id_key": "notification_id",
        "actor_id_key": "user_id",
    },
    # ── 審計日誌匯出事件 ──────────────────────────────
    "audit_log.log.exported": {
        "category": "audit_log",
        "action": "exported",
        "severity": "warning",
        "description": "審計日誌匯出",
        "resource_type": "audit_log",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
    # ── 社交登入事件 ──────────────────────────────────
    "auth.user.social_login": {
        "category": "auth",
        "action": "social_login",
        "severity": "info",
        "description": "社交帳號登入",
        "resource_type": "accounts.user",
        "resource_id_key": "user_id",
        "actor_id_key": "user_id",
    },
}
