# Generated by Django 5.2.12 on 2026-04-01 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="商品名稱")),
                ("slug", models.SlugField(max_length=200, unique=True, verbose_name="URL 別名")),
                ("description", models.TextField(blank=True, default="", verbose_name="商品說明")),
                (
                    "item_type",
                    models.CharField(
                        choices=[("one_time", "單次購買"), ("subscription", "訂閱制")],
                        default="one_time",
                        max_length=20,
                        verbose_name="商品類型",
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="作為顯示參考價格；實際收費以 PricingTier 為準",
                        max_digits=12,
                        verbose_name="基準定價",
                    ),
                ),
                (
                    "base_currency",
                    models.CharField(default="USD", max_length=3, verbose_name="基準幣別"),
                ),
                ("image_url", models.URLField(blank=True, default="", verbose_name="商品圖片")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品目錄",
                "db_table": "catalog_item",
                "ordering": ["sort_order", "base_amount"],
            },
        ),
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="例如「月繳」「年繳（8折）」",
                        max_length=100,
                        verbose_name="定價名稱",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="金額"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="幣別")),
                (
                    "billing_interval",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("day", "日繳"),
                            ("week", "週繳"),
                            ("month", "月繳"),
                            ("year", "年繳"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="計費週期",
                    ),
                ),
                (
                    "billing_interval_count",
                    models.PositiveIntegerField(default=1, verbose_name="每幾個週期收費"),
                ),
                (
                    "trial_period_days",
                    models.PositiveIntegerField(default=0, verbose_name="試用天數"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "catalog_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="catalog.catalogitem",
                        verbose_name="所屬商品",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_pricing_tier",
                "ordering": ["amount"],
            },
        ),
        migrations.CreateModel(
            name="GatewayPriceMapping",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("gateway", models.CharField(max_length=50, verbose_name="閘道名稱")),
                (
                    "gateway_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe price_xxx / ECPay 可留空",
                        max_length=200,
                        verbose_name="閘道端 Price ID",
                    ),
                ),
                (
                    "gateway_product_id",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="閘道端 Product ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pricing_tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateway_mappings",
                        to="catalog.pricingtier",
                        verbose_name="定價層級",
                    ),
                ),
            ],
            options={
                "db_table": "catalog_gateway_price_mapping",
                "unique_together": {("pricing_tier", "gateway")},
            },
        ),
    ]
