# Generated by Django 5.2.12 on 2026-03-24 07:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider_name", models.CharField(db_index=True, max_length=50)),
                ("api_key_encrypted", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("default_model", models.CharField(blank=True, max_length=100)),
                ("fallback_provider", models.CharField(blank=True, max_length=50)),
                ("settings_data", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_providers_config",
                "unique_together": {("owner", "provider_name")},
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider_name", models.CharField(db_index=True, max_length=50)),
                ("model", models.CharField(max_length=100)),
                ("prompt_tokens", models.IntegerField(default=0)),
                ("completion_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("request_type", models.CharField(max_length=20)),
                ("is_fallback", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_providers_usage",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="ai_provider_user_id_c2491a_idx"
                    ),
                    models.Index(
                        fields=["provider_name", "created_at"],
                        name="ai_provider_provide_09d918_idx",
                    ),
                ],
            },
        ),
    ]
