# Generated by Django 5.2.12 on 2026-04-28 05:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StylePreset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("key", models.SlugField(max_length=80, unique=True, verbose_name="識別碼")),
                ("name", models.CharField(max_length=120, verbose_name="名稱")),
                ("description", models.TextField(blank=True, default="", verbose_name="說明")),
                (
                    "resolution",
                    models.CharField(
                        default="16x16 resolution", max_length=80, verbose_name="解析度"
                    ),
                ),
                (
                    "palette_hex",
                    models.JSONField(blank=True, default=list, verbose_name="HEX 色盤"),
                ),
                (
                    "primary_palette",
                    models.TextField(blank=True, default="", verbose_name="主色盤"),
                ),
                (
                    "shadow_palette",
                    models.TextField(blank=True, default="", verbose_name="陰影色盤"),
                ),
                (
                    "accent_palette",
                    models.TextField(blank=True, default="", verbose_name="強調色盤"),
                ),
                (
                    "effect_palette",
                    models.TextField(blank=True, default="", verbose_name="特效色盤"),
                ),
                (
                    "art_direction",
                    models.TextField(blank=True, default="", verbose_name="藝術方向"),
                ),
                (
                    "background",
                    models.CharField(
                        default="plain transparent background",
                        max_length=160,
                        verbose_name="背景規則",
                    ),
                ),
                ("negative", models.TextField(blank=True, default="", verbose_name="負面提示詞")),
                (
                    "model_params",
                    models.JSONField(blank=True, default=dict, verbose_name="模型參數"),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="是否啟用"),
                ),
            ],
            options={
                "verbose_name": "風格預設",
                "verbose_name_plural": "風格預設",
                "db_table": "style_presets_style_preset",
                "ordering": ["key"],
            },
        ),
    ]
