# Generated by Django 5.2.12 on 2026-05-01 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_storage", "0001_initial"),
        ("style_presets", "0002_seed_initial_presets"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stylepreset",
            options={
                "ordering": ["sort_order", "key"],
                "verbose_name": "風格預設",
                "verbose_name_plural": "風格預設",
            },
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="is_system",
            field=models.BooleanField(db_index=True, default=True, verbose_name="是否系統內建"),
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="palette_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="色盤設定"),
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="preview_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="style_preset_previews",
                to="file_storage.filerecord",
                verbose_name="預覽圖",
            ),
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="processor_defaults",
            field=models.JSONField(blank=True, default=dict, verbose_name="預設處理器"),
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="prompt_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="Prompt 設定"),
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="sort_order",
            field=models.IntegerField(db_index=True, default=0, verbose_name="排序"),
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="target_config",
            field=models.JSONField(blank=True, default=dict, verbose_name="目標設定"),
        ),
        migrations.AddField(
            model_name="stylepreset",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="版本"),
        ),
    ]
