# Generated by Django 5.2.12 on 2026-04-28 05:27

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("subject", models.CharField(max_length=500, verbose_name="主題")),
                (
                    "preset_key",
                    models.CharField(db_index=True, max_length=80, verbose_name="風格預設"),
                ),
                ("view", models.CharField(default="top-down", max_length=40, verbose_name="視角")),
                (
                    "mode",
                    models.CharField(default="single", max_length=20, verbose_name="生成模式"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "已排隊"),
                            ("GENERATING", "生成中"),
                            ("PROCESSING", "處理中"),
                            ("ARCHIVED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        db_index=True,
                        default="ARCHIVED",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "prompt_snapshot",
                    models.TextField(blank=True, default="", verbose_name="提示詞快照"),
                ),
                (
                    "negative_prompt_snapshot",
                    models.TextField(blank=True, default="", verbose_name="負面提示詞快照"),
                ),
                (
                    "processors",
                    models.JSONField(blank=True, default=list, verbose_name="處理器快照"),
                ),
                (
                    "processor_config",
                    models.JSONField(blank=True, default=dict, verbose_name="處理器設定快照"),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="AI 供應商"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="模型"),
                ),
            ],
            options={
                "verbose_name": "資產",
                "verbose_name_plural": "資產",
                "db_table": "asset_library_asset",
                "ordering": ["-created_at"],
            },
        ),
    ]
