# Generated by Django 5.2.12 on 2026-04-28 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("asset_library", "0001_initial"),
        ("file_storage", "0001_initial"),
        ("generation_jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="generation_job",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset",
                to="generation_jobs.generationjob",
                verbose_name="來源生成任務",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="original_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_originals",
                to="file_storage.filerecord",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="processed_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_processed",
                to="file_storage.filerecord",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="thumbnail_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_thumbnails",
                to="file_storage.filerecord",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="使用者",
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["user", "status", "-created_at"], name="asset_libra_user_id_c745cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["preset_key", "-created_at"], name="asset_libra_preset__f1d936_idx"
            ),
        ),
    ]
