# Generated by Django 5.2.12 on 2026-04-01 12:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "catalog_item_id",
                    models.UUIDField(
                        blank=True,
                        help_text="對應 catalog.CatalogItem 的 ID",
                        null=True,
                        verbose_name="商品目錄項目",
                    ),
                ),
                (
                    "pricing_tier_id",
                    models.UUIDField(
                        blank=True,
                        help_text="對應 catalog.PricingTier 的 ID",
                        null=True,
                        verbose_name="定價方案",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待確認"),
                            ("trialing", "試用中"),
                            ("active", "啟用中"),
                            ("past_due", "付款逾期"),
                            ("paused", "已暫停"),
                            ("canceled", "已取消"),
                            ("expired", "已到期"),
                            ("terminated", "已終止"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="訂閱狀態",
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(blank=True, null=True, verbose_name="當前週期起始"),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="當前週期結束"),
                ),
                (
                    "trial_end",
                    models.DateTimeField(blank=True, null=True, verbose_name="試用結束時間"),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="取消時間"),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(default=False, verbose_name="期末取消"),
                ),
                (
                    "terminated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="終止時間"),
                ),
                (
                    "terminated_by",
                    models.CharField(blank=True, default="", max_length=50, verbose_name="終止者"),
                ),
                (
                    "gateway",
                    models.CharField(db_index=True, max_length=50, verbose_name="閘道名稱"),
                ),
                (
                    "gateway_subscription_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="閘道端訂閱 ID"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "訂閱",
                "verbose_name_plural": "訂閱",
                "db_table": "subscriptions_subscription",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPeriod",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("period_start", models.DateTimeField(verbose_name="週期起始")),
                ("period_end", models.DateTimeField(verbose_name="週期結束")),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="付款金額"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="幣別")),
                (
                    "payment_transaction_id",
                    models.UUIDField(
                        blank=True,
                        help_text="對應 payments.PaymentTransaction 的 ID",
                        null=True,
                        verbose_name="付款交易 ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "已付款"), ("unpaid", "未付款"), ("refunded", "已退款")],
                        default="unpaid",
                        max_length=20,
                        verbose_name="付款狀態",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="subscriptions.subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "訂閱週期",
                "verbose_name_plural": "訂閱週期",
                "db_table": "subscriptions_period",
                "ordering": ["-period_start"],
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "status"], name="subscriptio_user_id_2a19e8_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["gateway", "gateway_subscription_id"], name="subscriptio_gateway_4eb7c8_idx"
            ),
        ),
    ]
