# Generated by Django 5.2.12 on 2026-04-01 09:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                ("gateway", models.CharField(db_index=True, max_length=50)),
                (
                    "gateway_price_id",
                    models.CharField(
                        blank=True,
                        help_text="閘道端的價格 ID（如 Stripe price_xxx）",
                        max_length=200,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("month", "月繳"),
                            ("year", "年繳"),
                            ("week", "週繳"),
                            ("day", "日繳"),
                        ],
                        default="month",
                        max_length=20,
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveIntegerField(default=1, help_text="每幾個間隔收費一次"),
                ),
                ("trial_period_days", models.PositiveIntegerField(default=0, help_text="試用天數")),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "payments_subscription_plan",
                "ordering": ["amount"],
            },
        ),
        migrations.AlterField(
            model_name="paymentlog",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="payments.paymenttransaction",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待支付"),
                    ("success", "成功"),
                    ("failed", "失敗"),
                    ("expired", "過期"),
                    ("refunded", "已退款"),
                    ("partially_refunded", "部分退款"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("gateway", models.CharField(db_index=True, max_length=50)),
                (
                    "gateway_subscription_id",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("incomplete", "未完成"),
                            ("active", "啟用中"),
                            ("past_due", "付款逾期"),
                            ("canceled", "已取消"),
                            ("expired", "已到期"),
                            ("trialing", "試用中"),
                            ("paused", "已暫停"),
                            ("terminated", "已終止"),
                        ],
                        default="incomplete",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="payments.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "payments_subscription",
            },
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="payments.subscription",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="payments.subscription",
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["user", "status"], name="payments_su_user_id_058311_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["gateway", "gateway_subscription_id"], name="payments_su_gateway_4725d6_idx"
            ),
        ),
    ]
