# Generated by Django 5.2.12 on 2026-04-01 10:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_subscriptionplan_alter_paymentlog_transaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="商品名稱")),
                ("description", models.TextField(blank=True, default="", verbose_name="商品說明")),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="定價"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="幣別")),
                ("image_url", models.URLField(blank=True, default="", verbose_name="商品圖片 URL")),
                ("is_active", models.BooleanField(default=True, verbose_name="啟用")),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="額外資訊")),
            ],
            options={
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
                "db_table": "payments_product",
                "ordering": ["amount"],
            },
        ),
    ]
