# Generated by Django 5.2.12 on 2026-04-01 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookIdempotencyKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("gateway", models.CharField(max_length=50, verbose_name="閘道名稱")),
                (
                    "event_id",
                    models.CharField(
                        db_index=True,
                        help_text="如 Stripe 的 evt_xxx",
                        max_length=200,
                        verbose_name="閘道端事件 ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="事件類型"
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True, verbose_name="處理時間")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "處理中"),
                            ("completed", "已完成"),
                            ("failed", "失敗"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="處理狀態",
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="原始 Payload"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="錯誤訊息"),
                ),
            ],
            options={
                "verbose_name": "Webhook 冪等紀錄",
                "verbose_name_plural": "Webhook 冪等紀錄",
                "db_table": "payments_webhook_idempotency",
                "unique_together": {("gateway", "event_id")},
            },
        ),
    ]
