# Generated by Django 5.2.12 on 2026-04-01 12:40

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.payments.models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_webhookidempotencykey"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        default=core.payments.models.generate_order_number,
                        max_length=50,
                        unique=True,
                        verbose_name="訂單編號",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待支付"),
                            ("paid", "已付款"),
                            ("partially_refunded", "部分退款"),
                            ("refunded", "已退款"),
                            ("canceled", "已取消"),
                            ("expired", "已過期"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="訂單金額"),
                ),
                ("currency", models.CharField(default="USD", max_length=3, verbose_name="幣別")),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="訂單說明"
                    ),
                ),
                (
                    "catalog_item_id",
                    models.UUIDField(
                        blank=True, help_text="對應 catalog.CatalogItem 的 ID", null=True
                    ),
                ),
                (
                    "pricing_tier_id",
                    models.UUIDField(
                        blank=True, help_text="對應 catalog.PricingTier 的 ID", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="付款時間")),
                (
                    "expired_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="過期時間"),
                ),
            ],
            options={
                "verbose_name": "訂單",
                "verbose_name_plural": "訂單",
                "db_table": "payments_order",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="user",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="subscription",
        ),
        migrations.RemoveField(
            model_name="paymentlog",
            name="subscription",
        ),
        migrations.AlterModelOptions(
            name="paymentlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "金流日誌",
                "verbose_name_plural": "金流日誌",
            },
        ),
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={"verbose_name": "支付交易", "verbose_name_plural": "支付交易"},
        ),
        migrations.RemoveIndex(
            model_name="paymenttransaction",
            name="payments_tr_user_id_b99a80_idx",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="description",
        ),
        migrations.RemoveField(
            model_name="paymenttransaction",
            name="user",
        ),
        migrations.AlterField(
            model_name="paymentlog",
            name="action",
            field=models.CharField(max_length=50, verbose_name="操作類型"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="交易金額"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="currency",
            field=models.CharField(default="USD", max_length=3, verbose_name="幣別"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="gateway",
            field=models.CharField(db_index=True, max_length=50, verbose_name="閘道名稱"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="gateway_order_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, verbose_name="閘道端訂單 ID"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="付款時間"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="退款時間"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待支付"),
                    ("success", "成功"),
                    ("failed", "失敗"),
                    ("expired", "過期"),
                    ("refunded", "已退款"),
                    ("partially_refunded", "部分退款"),
                ],
                default="pending",
                max_length=20,
                verbose_name="交易狀態",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentlog",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="payments.order",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="order",
            field=models.ForeignKey(
                default="00000000-0000-0000-0000-000000000000",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="payments.order",
                verbose_name="所屬訂單",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="SubscriptionPlan",
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "status"], name="payments_or_user_id_0f08a8_idx"),
        ),
    ]
