# Generated by Django 5.2.12 on 2026-04-28 05:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("file_storage", "0001_initial"),
        ("style_presets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerationJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "已排隊"),
                            ("GENERATING", "生成中"),
                            ("PROCESSING", "處理中"),
                            ("ARCHIVED", "已完成"),
                            ("FAILED", "失敗"),
                        ],
                        db_index=True,
                        default="QUEUED",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="主題")),
                ("view", models.CharField(default="top-down", max_length=40, verbose_name="視角")),
                (
                    "mode",
                    models.CharField(default="single", max_length=20, verbose_name="生成模式"),
                ),
                ("prompt", models.TextField(blank=True, default="", verbose_name="完整提示詞")),
                (
                    "negative_prompt",
                    models.TextField(blank=True, default="", verbose_name="負面提示詞"),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="AI 供應商"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, default="", max_length=120, verbose_name="模型"),
                ),
                ("processors", models.JSONField(blank=True, default=list, verbose_name="處理器")),
                (
                    "processor_config",
                    models.JSONField(blank=True, default=dict, verbose_name="處理器設定"),
                ),
                (
                    "pipeline_warnings",
                    models.JSONField(blank=True, default=list, verbose_name="處理警告"),
                ),
                ("error", models.TextField(blank=True, default="", verbose_name="錯誤訊息")),
                ("percent", models.PositiveSmallIntegerField(default=0, verbose_name="進度")),
                ("retry_count", models.PositiveIntegerField(default=0, verbose_name="重試次數")),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=255),
                ),
                (
                    "result_asset_id",
                    models.UUIDField(blank=True, null=True, verbose_name="結果資產 ID"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, verbose_name="Metadata")),
                (
                    "archived_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="封存時間"),
                ),
                (
                    "original_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_original_jobs",
                        to="file_storage.filerecord",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="generation_jobs",
                        to="style_presets.stylepreset",
                        verbose_name="風格預設",
                    ),
                ),
                (
                    "processed_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_processed_jobs",
                        to="file_storage.filerecord",
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retry_jobs",
                        to="generation_jobs.generationjob",
                        verbose_name="來源任務",
                    ),
                ),
                (
                    "thumbnail_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_thumbnail_jobs",
                        to="file_storage.filerecord",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generation_jobs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
            ],
            options={
                "verbose_name": "生成任務",
                "verbose_name_plural": "生成任務",
                "db_table": "generation_jobs_generation_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status", "-created_at"],
                        name="generation__user_id_adb8b0_idx",
                    ),
                    models.Index(
                        fields=["preset", "-created_at"], name="generation__preset__8bd683_idx"
                    ),
                ],
            },
        ),
    ]
