# Generated by Django 5.2.12 on 2026-05-01 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_storage", "0001_initial"),
        ("generation_jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generationjob",
            name="metadata_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_metadata_jobs",
                to="file_storage.filerecord",
            ),
        ),
        migrations.AlterField(
            model_name="generationjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "已排隊"),
                    ("PLANNING", "提示詞規劃中"),
                    ("GENERATING", "生成中"),
                    ("PROCESSING", "處理中"),
                    ("ARCHIVED", "已完成"),
                    ("FAILED", "失敗"),
                    ("DISMISSED", "已移除"),
                ],
                db_index=True,
                default="QUEUED",
                max_length=20,
                verbose_name="狀態",
            ),
        ),
    ]
