# Generated by Django 5.2.12 on 2026-03-31 05:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, verbose_name="名稱")),
                (
                    "key_prefix",
                    models.CharField(db_index=True, max_length=12, verbose_name="金鑰前綴"),
                ),
                ("key_hash", models.CharField(max_length=64, unique=True, verbose_name="金鑰雜湊")),
                ("description", models.TextField(blank=True, default="", verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "啟用"),
                            ("disabled", "停用"),
                            ("revoked", "已撤銷"),
                            ("expired", "已過期"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="狀態",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="過期時間"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="撤銷時間"),
                ),
                ("scopes", models.JSONField(blank=True, default=list, verbose_name="權限範圍")),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="留空使用系統預設值",
                        null=True,
                        verbose_name="每分鐘請求上限",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="最後使用時間"),
                ),
                (
                    "last_used_ip",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="最後使用 IP"),
                ),
                ("usage_count", models.PositiveIntegerField(default=0, verbose_name="使用次數")),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="支援 CIDR 格式",
                        verbose_name="允許的 IP 清單",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="擁有者",
                    ),
                ),
                (
                    "replaced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replaces",
                        to="api_keys.apikey",
                        verbose_name="被替換為",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="APIKeyUsageLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="時間戳記"),
                ),
                ("endpoint", models.CharField(max_length=200, verbose_name="端點")),
                ("method", models.CharField(max_length=10, verbose_name="HTTP 方法")),
                ("status_code", models.PositiveIntegerField(verbose_name="狀態碼")),
                ("ip_address", models.GenericIPAddressField(null=True, verbose_name="IP 位址")),
                ("user_agent", models.TextField(blank=True, default="", verbose_name="User Agent")),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(null=True, verbose_name="回應時間（毫秒）"),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="api_keys.apikey",
                        verbose_name="API Key",
                    ),
                ),
            ],
            options={
                "verbose_name": "API Key 使用紀錄",
                "verbose_name_plural": "API Key 使用紀錄",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["owner", "status"], name="api_keys_ap_owner_i_55625c_idx"),
        ),
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["key_hash"], name="api_keys_ap_key_has_da7081_idx"),
        ),
        migrations.AddIndex(
            model_name="apikeyusagelog",
            index=models.Index(
                fields=["api_key", "-timestamp"], name="api_keys_ap_api_key_02e4ae_idx"
            ),
        ),
    ]
