# Generated by Django 5.2.12 on 2026-03-31 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100, verbose_name='事件類型')),
                ('category', models.CharField(choices=[('auth', '認證'), ('account', '帳號'), ('data', '資料操作'), ('payment', '金流'), ('admin', '管理操作'), ('security', '安全事件'), ('system', '系統事件')], db_index=True, max_length=20, verbose_name='事件分類')),
                ('severity', models.CharField(choices=[('info', '資訊'), ('warning', '警告'), ('critical', '嚴重')], default='info', max_length=10, verbose_name='嚴重程度')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('actor_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='操作者 ID')),
                ('actor_email', models.CharField(blank=True, default='', max_length=255, verbose_name='操作者信箱')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='操作者 IP')),
                ('actor_user_agent', models.TextField(blank=True, default='', verbose_name='User Agent')),
                ('resource_type', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='資源類型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=100, verbose_name='資源 ID')),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='操作')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='變更內容')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件資料')),
                ('request_id', models.CharField(blank=True, default='', max_length=50, verbose_name='請求 ID')),
                ('source_event_id', models.CharField(blank=True, default='', max_length=50, verbose_name='來源事件 ID')),
            ],
            options={
                'verbose_name': '審計記錄',
                'verbose_name_plural': '審計記錄',
                'db_table': 'audit_log_auditentry',
                'ordering': ['-created_at'],
                'default_permissions': ('add', 'view'),
                'indexes': [models.Index(fields=['actor_id', '-created_at'], name='audit_log_a_actor_i_8d432d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_log_a_resourc_81c12a_idx'), models.Index(fields=['category', '-created_at'], name='audit_log_a_categor_e27ebc_idx'), models.Index(fields=['event_type', '-created_at'], name='audit_log_a_event_t_9c043b_idx')],
            },
        ),
    ]
